### ISSUE TITLE
Add event listener for <checkbox> for Dark Theme

### ISSUE THREAD

**Issue by asimonia** [nss-day-cohort-16/d16-gp-chatty-aim#11]
goDark():
Change the background color of your application to a dark gray, and the font color for messages should be white

These should toggle.

When the user unchecks the box, the background will be white and the font color will be black

**Comment by stevenwally** [comment]
Event listener is functional. Need to add CSS styling for toggling between dark theme and regular theme.

**Comment by TrentHand** [comment]
This is up and running.
