### ISSUE TITLE
Add event listener for <checkbox> for Large Text

### ISSUE THREAD

**Issue by asimonia** [nss-day-cohort-16/d16-gp-chatty-aim#12]
place under events.js

Increase the font size of the text when this box is checked.  When unchecked, go back to the default size.

**Comment by stevenwally** [comment]
UPDATE:
the function that is called when the checkbox is clicked is now 'largeFunc()'

**Comment by stevenwally** [comment]
Need to add CSS to function before this can be marked as complete.
