### ISSUE TITLE
Create a global var named Chatty

### ISSUE THREAD

**Issue by asimonia** [nss-day-cohort-16/d16-gp-chatty-aim#16]
Create multiple IIFEs, following the Single Responsibility Principle, that perform the following functions. The name of your global variable that gets augmented by the IIFEs should be Chatty.

var Chatty = (function() {
    var privateVariable = [];

```
return {    //object goes here  };
```

})();

**Comment by stevenwally** [comment]
var Chatty = {};

**Comment by TrentHand** [comment]
added and should be done.
