### ISSUE TITLE
IIFE (2 of 3): messageHandler

### ISSUE THREAD

**Issue by asimonia** [nss-day-cohort-16/d16-gp-chatty-aim#18]
One IIFE should contain a function that accepts an element id, and the user message, and then add the user's message - along with the delete button - to the specified parent element. Each message should be stored in a private array in this IIFE. This IIFE should also expose a function to read all messages, and delete a single message.

**Comment by TrentHand** [comment]
Create button after each message to delete the above message 
delete message "BTNname"
deleteMessage()
